### ISSUE TITLE
How to edit database

### ISSUE THREAD

**Issue by amokster88** [zluckytraveler/Discord-Plex-Trial#1]
How! to edit and remove users from database?

**Comment by amokster88** [comment]
I can't understand the users.db file and how to remove users from it

**Comment by zluckytraveler** [comment]
> I can't understand the users.db file and how to remove users from it

You would need to know how to use SQLite, and depend on the program you use, that is something I cannot really help you with.

**Comment by amokster88** [comment]
Can you all add commands, so that we can remove the user from db, with commands. For eg:- !bot remove ‘discord user’

**Comment by zluckytraveler** [comment]
> Can you all add commands, so that we can remove the user from db, with commands. For eg:- !bot remove ‘discord user’

I will not be adding on to this project, it is open source, so you can add your own commands as you'd like, or just simply the edit the database file directly as it was intended.
